### ISSUE TITLE
Question about how to implement this mod into the Campaign mod.

### ISSUE THREAD

**Issue by NikolayByondPlayer** [TripsLetash/WotF-Goblins#1]
Hello! Sorry this isn't an issue but a question: 
Do you know how to add this mod into the WIP mod in Baldurs Gate 3 Modding tool?

**Comment by TripsLetash** [comment]
I do. I shall perhaps do it when I find time. I do not give permission for anyone else to do so

**Comment by NikolayByondPlayer** [comment]
Do you know how to make standart goblins from BG3 wear equipped armour? 
Do I need to assign them different skeleton (like halfling maybe)?

**Comment by NikolayByondPlayer** [comment]
Found a way to make gob race in editor without mod
